FROM ubuntu:latest

# Installer les outils nécessaires pour vos tests
RUN apt-get update && apt-get install -y curl jq

# Installer Docker CLI
RUN apt-get update && apt-get install -y \
    curl \
    && curl -fsSL https://get.docker.com -o get-docker.sh \
    && sh get-docker.sh

# Installer Docker Compose
RUN curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose \
    && chmod +x /usr/local/bin/docker-compose

# Copiez vos scripts de test dans l'image
COPY run_tests.sh /run_tests.sh

# Rendez le script exécutable
RUN chmod +x /run_tests.sh

# Commande par défaut pour exécuter lors du démarrage du conteneur
CMD ["/run_tests.sh"]
