# Utilisez l'image de base Python
FROM python:3.8

# Copiez le code source dans le conteneur
COPY ./app_display_product /app

# Définissez le répertoire de travail
WORKDIR /app

# Installez les dépendances
RUN pip install -r requirements.txt

# Exposez le port sur lequel l'application Flask s'exécute
EXPOSE 5002

# Commande pour exécuter l'application Flask
CMD ["python", "app.py"]
