# Utilisez une image de base Python
FROM python:3.8

# Copiez le code source dans le conteneur
COPY ./app_read_product /app

# Définissez le répertoire de travail
WORKDIR /app

# Installez les dépendances
RUN pip install -r requirements.txt

# Exposez le port
EXPOSE 5001

# Commande pour exécuter le service
CMD ["python", "app.py"]
